### PR TITLE
Upgraded contract libraries, bumped to Solidity 0.8.0, and updated allowed Yarn / Node versions

### PR DESCRIPTION
**Pull request by TheMaxKim**
* Replaced multi-token-standard package for ERC1155 token contracts with OpenZeppelin versions.

* Removed custom Strings library and replaced String concatenation with the following: https://forum.openzeppelin.com/t/add-support-for-erc721-token-uri-concatenation-of-base-token-uri-and-tokenid/566/10

* Modified multiline comments where appropriate from `/**` to `/*` because those are parsed as natspec: https://docs.soliditylang.org/en/v0.5.8/natspec-format.html. Which is quite picky and doesn't seem to let you document non public state variables.

* Added Solidity compilation optimization due to contract size limitations being reached with CreatureAccessoryLootBox.sol.

* Updated ERC1155 Metadata URI standard to use the substitution method, based on OZ sample as well as the standard defined below (Kept CreatureAccessoryFactory's custom URI logic as a sample of overriding it and using the old pattern of constructing the final URI in the smart contract):
  * https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v4.0.0/contracts/token/ERC1155/extensions/IERC1155MetadataURI.sol
  * https://eips.ethereum.org/EIPS/eip-1155#metadata

* Tried to minimize compiler warnings, but two still exist due to unused arguments.

* Updated various tests:
  * Emitted event filters had to be updated as field names changed a bit.
  * Added tests for new URI standard support.
  * Math checked by default in Solidity 0.8.0+ makes the error to check different, since SafeMath doesn't return its own error: https://blog.soliditylang.org/2020/12/16/solidity-v0.8.0-release-announcement/
 
Also tested by deploying the various contracts to Rinkeby:
* [Creature contract](https://rinkeby.etherscan.io/tx/0xb86ab826e96c5e8d78e457ba31501165b102063ceb8e491e234e4c607f29c78e)
* [CreatureFactory contract](https://rinkeby.etherscan.io/tx/0x278d5ed79e10d3b36be73fced8de143fa14f14b86979e07d598c09f4be24613f)
* [CreatureAccessory contract](0xbba908ec8dc7d0d13974f2e72282f35b140ec3d9fb3e0c0578fc64df23f2f8af)
* [LootBoxRandomness contract](https://rinkeby.etherscan.io/tx/0x8d6085df0a7db4b56a24e86c2b488df914a70530951a592f9ecdffe0f99a1379)
* [CreatureAccessoryLootBox contract](https://rinkeby.etherscan.io/tx/0x2642834879479213090b88b5e337e6e40c2786194ec6c29247d12ca272d2820c)
* [CreatureAccessoryFactory contract](https://rinkeby.etherscan.io/tx/0x12ddc2f1834971d1c6d1a2afb62d3fd23aaf8ad7319743bba261180b956101c2)

Minted some creatures / lootboxes with the factory mint.js script:
* Creature: https://testnets.opensea.io/assets/0x41bf5b0bd9d22f33f8aa20ae21be79feba26dbe1/1
* Lootbox: https://testnets.opensea.io/assets/0x81e7ab38ea3fc73aacde63707fdf6bde40f2d9ea/1
* Accessory: https://testnets.opensea.io/assets/0xe9a04397b54a67591a93115328adc6cf7a4fa49d/0

Versus some I created weeks ago:
* Creature: https://testnets.opensea.io/assets/0xee1123b5e0fa8ae33ff1812e0c618c28ab926424/1
* Lootbox: https://testnets.opensea.io/assets/0x50477b3fe06b259844bb0932a98883af6eeb4ba7/1

Transferred a creature: https://rinkeby.etherscan.io/tx/0x02432922d1f7f1eb26d1c06f59325a8d72f58e2a08bc307c501af5d406cbd7be

### CODE REVIEW

**Review by sunwrobert — APPROVED** [review]
thanks for doing this, this is big

**Comment by tobek** [comment]
I think this PR broke buying on OpenSea, see issue https://github.com/ProjectOpenSea/opensea-creatures/issues/68 - it worked before this PR but not after (I haven't done a git bisect or anything so not sure of exact commit).

@TheMaxKim to confirm, try listing one of your creatures on https://testnets.opensea.io/collection/opensea-creatures-0kiaooeuhz for sale and seeing if you can buy it.

**Comment by TheMaxKim** [comment]
Hey @tobek , thanks for the heads up, I'll give it a shot tonight and post back.

**Comment by remiroyc** [comment]
Do you have any news @TheMaxKim? Tell me if I can help in some way

**Pull request merged**
